### ISSUE TITLE
Đăng nhập

### ISSUE THREAD

**Issue by ngochihieu281200** [ngochihieu281200/QUANLYRESORT#144]
giao diện:
 - col-6 logo của khách sạn
 - col-6 các thông tin 
    + đăng nhập  username input type="text",
    +  password input type=" password ", 
    + input type=" radio " ghi nhớ mật khẩu, 
    + button  " đăng nhập " 

 xử lý: 
- kiểm tra điền tài khoản hoặc mật khẩu có đúng với thông tin ở database của bảng taikhoan không, nếu điền không đúng sẽ báo tài khoản mật khẩu sai.
- click vào button "đăng nhập "  đúng tài khoản mật khẩu   đưa  đến trang chủ của admin.
 
lưu trữ: không.

**Comment by thuando2120** [comment]
đã nhận task
