### ISSUE TITLE
tra cứu phòng

### ISSUE THREAD

**Issue by ngochihieu281200** [ngochihieu281200/QUANLYRESORT#147]
Giao diện: 
- title thêm tra cứu phòng.
 - 2 label gồm ( tình trạng , loại phòng) , 
   - 1 input type=" radio " cho tình trạng ( đang sử dụng hoặc trống) , 
   - 1 option cho loại phòng.
- 2 button (  button tìm kiếm  và button  nhập mới )

Xử lý: 
- tìm kiếm theo trạng thái: chọn trạng đang sử dụng , click vào button "tìm kiếm"  hiển thị danh sách có trạng thái đang sử dụng.  chọn trạng thái trống  , click vào button "tìm kiếm"  hiển thị danh sách có trạng thái trống.
- tìm kiếm theo loại phòng:  click vào option loại phòng hiện list loại phòng , chọn 1 loại phòng trong  danh sách loại phòng , click vào button  " tìm kiếm " hiển thị 1 danh sách loại  phòng đã chọn.  

- click button " tìm kiếm "   kiểm tra thông tin cần tìm ở bảng  phong và đưa ra màn hình
- click button " nhập mới " reset lại bảng tìm kiếm. 

lưu trữ: không

**Comment by thuando2120** [comment]
đã nhận
