### ISSUE TITLE
Chi tiết phòng

### ISSUE THREAD

**Issue by ngochihieu281200** [ngochihieu281200/QUANLYRESORT#148]
giao diện: 
- title " chi tiết phòng "
-  6 label gồm ( hình ảnh,  mã phòng, loại phòng , đơn giá, sức chứa, mô tả ).
- 2 button ( button sửa, button trở về )

xư lý: lấy thông tin từ bảng phong và loaiphong
- click vào button " sửa"  chuyển qua trang sửa phòng.
- click vào button " quay về " quay về trang danh sách phòng.

lưu trữ: không.

**Comment by thuando2120** [comment]
đã nhận
