### ISSUE TITLE
Chi tiết loại phòng

### ISSUE THREAD

**Issue by thuando2120** [ngochihieu281200/QUANLYRESORT#155]
giao diện: 
- title " chi tiết phòng " 
- 6 label ( hình ảnh,mã loại phòng , tên loại phòng , đơn giá, sức chứa mô tả )
- 2 button ( button sửa và button trở về )

xử lý: lấy từ bảng loaiphong
- click vào button " sửa"  chuyển qua trang sửa loại phòng.
- click vào button " quay về " quay về trang danh sách loại phòng.

lưu trữ : không

**Comment by ngochihieu281200** [comment]
đã nhận task
