### ISSUE TITLE
Danh sách nhân viên

### ISSUE THREAD

**Issue by thuando2120** [ngochihieu281200/QUANLYRESORT#165]
giao diện:  title " danh sách nhân viên (ở đầu trang) " ,
- 1 link thêm mới nhân viên, 
- 1 link tìm kiếm nhân viên,
- bảng danh sách nhân viên gồm ( STT, mã nhân viên, tên nhân viên , giới tính,ngày sinh, địa chỉ  , email, số điện thoại  hình ảnh, chức năng (sửa, xóa)). 

xử lý: lấy từ bảng nhanvien

- khi bấm vào linh thêm mới nhân viên thì chuyển ta qua tab thêm mới nhân viên, 
- khi bấm tìm kiếm khách hàng thì chuyển ta đến tab tìm kiếm nhân viên.
- bảng danh sách cho hiện ( STT, mã nhân viên, tên nhân viên , giới tính,ngày sinh, địa chỉ  , email, số điện thoại  hình ảnh, chức năng (sửa, xóa)) ở database ở bảng danh sách nhanvien lên màn hình.
- click vào biểu tượng cây bút có chức năng cập nhật chuyển qua trang chỉnh sửa nhân viên.
- click vào biểu tượng cuốn sổ có chức nặng xem chi tiết chuyển qua trang chi tiết  nhân viên.
- click vào biểu tượng thùng rác có chức nặng xóa chuyển qua trang xóa nhân viên. 

lưu trữ: không

**Comment by ngochihieu281200** [comment]
đã nhận task
