### ISSUE TITLE
danh  sách phiếu đặt phòng

### ISSUE THREAD

**Issue by truongloi1005** [ngochihieu281200/QUANLYRESORT#171]
giao diện: 
- title " danh sách phiếu đặt phòng (ở đầu trang) " ,
- 1 link thêm mới phiếu đặt phòng dưới title danh sách phiếu đặt phòng,  
- bảng danh sách phiếu đặt phòng  gồm ( STT, mã  phiếu đặt , ngày đến, ngày đi, tiền cọc , số người, tình trạng , khách hàng , nhân viên , chức năng (sửa, xem chi tiết, xóa)). 

xử lý:
- khi bấm vào link thêm mới phiếu  đặt phòng chuyển  qua tab thêm mới phiếu đặt phòng.
-  bảng danh sách cho hiện  ( STT, mã  phiếu đặt , ngày đến, ngày đi, tiền cọc , số người, tình trạng , khách hàng , nhân viên , chức năng (sửa, xóa)) từ  database bảng danh sách phiếu đăt phòng  lên màn hình.
- click vào biểu tượng cây bút có chức năng cập nhật chuyển qua trang chỉnh sửa phiếu đặt phòng.
- click vào biểu tượng chấm thang có chức nặng xem chi tiết chuyển qua trang chi tiết phiếu đặt phòng.
- click vào biểu tượng thùng rác có chức nặng xóa chuyển qua trang xóa phiếu đặt phòng. 

lưu trữ: không.

**Comment by thuando2120** [comment]
đã nhận task
