### ISSUE TITLE
sử dụng dịch vụ

### ISSUE THREAD

**Issue by truongloi1005** [ngochihieu281200/QUANLYRESORT#172]
giao diện:
- 1 title " sử dụng dịch vụ "
- có 5 label ( mã phiếu thuê, mã phòng, mã dịch vụ, ngày sử dụng, số lượng )
  + 1 input có type="text" cho mã phiếu thuê phòng bị khóa. 
  + 2 select option cho ( mã phòng và  mã dịch vụ )
  + 1 input có type=" datetime-local ' cho ngày trả 
  + 1 input có type= "number " cho số lượng.
- 2 button ( button thêm và button trở về )

xử lý: 
- input mã phiếu thuê phòng bị khóa k cho nhập.
- click vào mã phòng sổ 1 list mã phòng lấy tư  bảng phòng .
- click vào mã dịch vụ  sổ 1 list dịch vụ cho chọn lấy từ bảng dichvu
- số lượng nhập >=1
- click button " thêm " thêm dịch vụ sử dụng vào dabase bảng [CTPhieuThuePhong]], và hiện thị ra danh sách phiếu thuê phòng.
- click vào button "trở về " quay về trang chi tiết phiếu thuê phòng.

lưu trữ : lưu dịch vụ sử dụng vào database bảng [CTPhieuThuePhong]],

**Comment by thuando2120** [comment]
đã nhận task
