### ISSUE TITLE
chi tiết phiếu đặt phòng

### ISSUE THREAD

**Issue by truongloi1005** [ngochihieu281200/QUANLYRESORT#175]
giao diện :

- title " thông tin phiếu đặt phòng "
   + col-6 gồm các label  ( mã phiếu đặt phòng,  , ngày đến  , số người,  nhân viên)
   + col-6 gồm các label ( tên khách hàng, ngày đi , tình trạng )
- 1 tile  chi tiết phiếu đặt phòng
- 1 link " đặt  thêm phòng " ở phía dưới  tile  " chi tiết phiếu đặt phòng",
-  hiển thị dưới dạng danh sách có các cột ( stt,  mã phòng, tiền cọc , loại phòng, sức chứa, 1 chức năng xóa  ).
 1tile tổng tiền cọc nằm bên trái dưới bảng danh sách chi tiết phiếu đặt phòng.
- có 2 button ( button sửa và button trở về )

xử lý: lấy thông tin từ bảng [PhieuDatPhong] , [CTPhieuDatPhong]
- click vào link " đặt thêm phòng " chuyển qua trang đặt thêm phòng.
- click vào biểu tưởng thùng rác chức năng xóa, chuyển qua trang xóa.
- click vào button " sửa " chuyển qua trang sửa phiếu đặt phòng.
- click vào button " trở về " quay về danh sách phiếu đặt phòng.

lưu trữ: không

**Comment by thuando2120** [comment]
đã nhận task
