### ISSUE TITLE
đăt thêm phòng

### ISSUE THREAD

**Issue by truongloi1005** [ngochihieu281200/QUANLYRESORT#177]
giao diện: 
- tile " đặt thêm phòng"
- 3 label ( mã phiếu đặt phòng, mã phòng, tiền cọc )
  + 1 input có type=" text" cho mã phiếu đặt phòng bị khóa.
  + 1 select option  cho mã phòng.
  + 1 input có type=" number " cho tiên cọc
- 2 button ( button thêm và button trở về )

xử lý: 
- input mã phiếu đặt phùng bị khóa  lấy mã từ phiếu đặt phòng 
- click vào option hiển thị 1 list danh sách phòng lấy mã phòng từ bảng phong.
- tiền cọc tự điền mặc định 300000
- click vào button " thêm  " lưu  vào database bảng [CTPhieuDatPhong]
- click vào button " trở về " quay về trang chi tiết phiếu đặt phòng

lưu: lưu vào database bảng [CTPhieuDatPhong]

**Comment by thuando2120** [comment]
đã nhận task
