### ISSUE TITLE
sửa dịch vụ

### ISSUE THREAD

**Issue by truongloi1005** [ngochihieu281200/QUANLYRESORT#182]
giao diện: 
- title " sửa dịch vụ "
- 3 label gồm ( maDV, tên dịch vụ , giá ).
 + 1 input type="text" ch maDV bị khóa.
 + 1 input type="text" cho tên dịch vụ.
 + 1 input type=" number " cho đơn giá
- 2 button ( button cập nhật và button trở về  )

Xử lý: lấy thông tin từ bảng dichvu
- click vào button " cập nhật " lưu thông tin mới của dịch vụ vào database bảng dichvu và hiển thị trên danh sách dịch vụ.
- click vào button " trở về " quay về trang danh sách dịch vụ.

lưu trữ : cập nhật lại thông tin dịch vụ vào database ở bảng  dichvu

**Comment by ngochihieu281200** [comment]
đã nhận task
