### ISSUE TITLE
xóa dịch vụ

### ISSUE THREAD

**Issue by truongloi1005** [ngochihieu281200/QUANLYRESORT#183]
giao diện: 
- title "  xác nhận xóa dịch vụ " Bạn có chắc là muốn xóa dịch vụ này?
- 3 label gồm ( maDV, tên dịch vụ , giá ).
- 2 button ( button xóa và button trở về  )

Xử lý: lấy thông tin từ bảng dichvu
- click vào button "xoá"  xoá dịch vụ khỏi view danh sách dịch vụ.
- click vào button " trở về " quay về trang danh sách dịch vụ.

lưu trữ: không

**Comment by ngochihieu281200** [comment]
đã nhận task
