### ISSUE TITLE
thêm mới phiếu thuê phòng

### ISSUE THREAD

**Issue by truongloi1005** [ngochihieu281200/QUANLYRESORT#184]
giao diện : 
- tile " thêm mới phiếu thuê phòng "
- gồm 2 phần: 
   + phần 1:title phiếu thuê phòng:
      - col-6: 
         + gồm  3 label ( mã phiếu thuê phòng,  mã phiếu đặt phòng, ngày thuê )
            + 1 input  type="text" cho ( mã phiếu thuê phòng ) bị khóa.
            +  1 select option cho mã phiếu đặt phòng.
            + 1 input type=" datetime" cho ( ngày thuê )
       - col-6:
         + gồm 3 label ( mã nhân viên, mã khách hàng, ngày trả )
           + 1 option cho  ( mã khách hàng ) .
           + 1 input type="datetime" cho ( ngày trả )
           + 1 input có type = " text  " cho mã nhân viên bị khóa
 + phần 2: tile " chi tiết phiếu thuê phòng "
        - col-3 : label  phòng ( option  )  
        - col-3 : label dịch vụ ( select option )
        - col-3 :  label ngày sử dụng ( input type=" datetime-local " )
       -col-3: label  số lượng ( input type=" number " )
       - button "thêm"
        - danh sách phòng và tiền cọc: gồm  4 label  (phòng,dịch vụ , ngày sử dụng, số lượng, 1 chức năng remove)
     
- 2 button ( button lưu và button trở về)

**Comment by thuando2120** [comment]
đã nhận task
