### ISSUE TITLE
xóa tài khoản

### ISSUE THREAD

**Issue by truongloi1005** [ngochihieu281200/QUANLYRESORT#191]
giao diện: 
- title "Bạn có chắc chắn xóa thông tin này?"
- title " thông tin chi tiết "
- có 5 label gồm ( tên đăng nhập, mật khẩu , tình trạng , mã nhân viên, idnhom,  
- 2 button ( button xóa và button trở về )

xư lý : lấy thông tin tử database bảng taikhoan
- click vào button "xoá"  xoá tài khoản khỏi view danh sách  tài khoản.
- click vào button " trở về " quay về trang   danh sách tài khoản.

lưu trữ : không

**Comment by ngochihieu281200** [comment]
đã nhận task
