### ISSUE TITLE
Danh sách nhóm nhân viên

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#193]
giao diện:  
- title " danh sách nhóm  nhân viên (ở đầu trang) " , 
- 1 link thêm mới nhóm nhân viên ở dưới tile " danh sách nhóm nhân viên", 
-  bảng danh sách nhóm nhân viên  gồm ( STT, mã nhóm nhân viên, tên nhóm nhân viên , chức năng ( xóa)). 

xử lý:
-  khi bấm vào link thêm mới nhóm nhân viên  chuyển  qua tab thêm mới  nhóm nhân viên. 
- bảng danh sách nhóm nhân viên cho hiện ( STT, mã nhóm nhân viên, tên nhóm nhân viên , chức năng ( xóa)).  từ database ở bảng nhom nhan viên lên màn hình.
- click vào biểu tượng xóa chức năng xóa chuyển qua trang xóa nhóm nhân viên.

lưu trữ: không.

**Comment by ngochihieu281200** [comment]
đã nhận task
