### ISSUE TITLE
Thêm mới nhóm nhân viên

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#194]
giao diện: 
- title "thêm mới nhóm nhân viên"
- 2 label gồm ( id nhóm, tên nhóm,  ) và 2 input type="text" tương ứng
- 2 button (button thêm mới và button trở về)

xử lý:
- nhập idnhom và tên nhóm
- click vào button "thêm mới" lưu thông tin nhóm nhân viên vào database ở bảng [NhomNhanVien].
- click vào button " trở về " trở về trang danh sách nhóm nhân viên

lưu trữ: lưu thông tin tài khoản vào database ở bảng [NhomNhanVien].

**Comment by ngochihieu281200** [comment]
đã nhận task
