### ISSUE TITLE
Xóa nhân viên

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#195]
giao diện: 
- title " xóa nhóm nhân viên
Bạn chắc chắc muốn xóa thông tin này?"

- 2 label gồm ( id nhóm, tên nhóm,  ) 
- 2 button (button xóa và button trở về)

xư lý : lấy thông tin từ database bảng [NhomNhanVien]
- click vào button "xoá"  xoá nhóm nhân viên khỏi view danh sách  nhóm nhân viên.
- click vào button " trở về " quay về trang   danh sách nhóm nhân viên
lưu trữ: không

**Comment by ngochihieu281200** [comment]
đã nhận task
