### ISSUE TITLE
Danh sách phân quyền

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#196]
giao diện:  
- title " danh sách phân quyền (ở đầu trang) " ,
- 1 link thêm mới phần quyền bên dưới title danh sách phân quyền, 
-  bảng danh sách phân quyền  gồm ( STT, nhóm nhân viên, quyền , chức năng ( xóa)). 

xử lý:
- khi bấm vào link thêm mới  phân quyền  chuyển  qua tab thêm mới  phân quyền.
- bảng danh sách phân quyền cho hiện ( STT, nhóm nhân viên, quyền , chức năng ( xóa)). từ database  ở bảng PhanQuyen lên màn hình.
- click vào biểu tượng xóa chức năng xóa chuyển qua trang xóa phân quyền.
lưu trữ: không.

**Comment by thuando2120** [comment]
đã nhận task
