### ISSUE TITLE
Thêm mới phân quyền

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#197]
giao diện: 
- tile "Thêm mới quyền cho nhóm nhân viên"
- 2 label gồm ( id nhóm, idquyen, ) , tương ứng 2 select option
- 2 button ( button thêm mới và button trở về) 

xử lý: 
- click vào option idnhom sổ 1 list nhóm , lấy từ database ở bảng nhóm nhân viên (tên nhóm nhân viên).
- click vào option idquyen sỏ 1 list quyền , lấy từ database ở bảng danhsachquyen
- click vào button "thêm" được lưu vào database ở bảng Quyen và hiển thị ra danh sách nhóm phân quyền.
- click vào button "trở về" quay về trang danh sách nhóm phân quyền.

lưu trữ: lưu thông tin phân quyền vào database ở bảng Quyen.

**Comment by thuando2120** [comment]
đã nhận task
