### ISSUE TITLE
Xóa phân quyền

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#198]
giao diện: 
- title "Bạn có chắc chắn muốn xóa thông tin này?"

- 2 label gồm ( nhóm nhân viên, quyền,  ) 
- 2 button (button xóa và button trở về)

xư lý : lấy thông tin từ database bảng [Quyen]
- click vào button "xoá"  xoá Phân quyền khỏi view danh sách phân quyền .
- click vào button " trở về " quay về trang   danh sách phân quyền
lưu trữ: không

**Comment by thuando2120** [comment]
đã nhận task
