### ISSUE TITLE
Chi tiết liên hệ

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#202]
giao diện: 
- tile " chi tiết liên hệ  "
- có 5 label ( Họ tên, số điện thoại, email, ngày gửi, tình trạng phòng )
- button trở về 

xử lý: lấy thông tin người liên hệ từ database bảng lienhe.
- click vào button " trở về " quay về trang danh sách liên hệ.

lưu trữ: không

**Comment by ngochihieu281200** [comment]
đã nhận task
