### ISSUE TITLE
Sửa phản hồi

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#204]
giao diện: 
- tile " chỉnh sửa phản hồi  "
- có 6 label ( Họ tên, số điện thoại, email, nội dung, ngày gửi, tình trạng)
  + 5 input có type="text" cho  ( Họ tên, số điện thoại, email, nội dung, ngày gửi, ) và bị khóa.
  + 2 input có type="radio" ( đã xử lý , chưa xử lý ) cho tình trạng .
- có 2 button ( button lưu và button trở về )

xử lý: lấy từ bảng phanhoi
- input (Họ tên, số điện thoại, email, nội dung, ngày gửi, ) và bị khóa. không được sửa
- chỉ cho sửa tình trạng  , thay đổi từ trạng thái đã xử lý sang chưa xử lý và ngược lại.
- click vào button " lưu "  cập nhật trạng thái  lại ở database bảng phanhoi  và hiển thị danh sách phản hồi.
- click vào button "trở về" quay về trang danh sách liên hệ

xử lý: cập nhật lại thông tin trạng thái  vào database ở bảng phanhoi

**Comment by thuando2120** [comment]
đã nhận task
