### ISSUE TITLE
Xóa phản hồi

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#205]
giao diện: 
- tile " Xóa phản hồi  " Bạn có chắc chắn muốn xóa thông tin này?.
- có 6 label ( Họ tên, số điện thoại, email, nội dung, ngày gửi, tình trạng)
- có 2 button ( button lưu và button trở về )

xử lý: lấy thông tin người phản hồi từ database bảng phanhoi.
- click vào button "xoá"  xoá phản hồi khỏi view danh sách phản hồi.
- click vào button " trở về " quay về trang danh sách phản hồi.

lưu trữ: không

**Comment by ngochihieu281200** [comment]
đã nhận task
