### ISSUE TITLE
Chi tiết phản hồi

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#206]
giao diện: 
- tile " chi tiết phản hồi "
- có 6 label ( Họ tên, số điện thoại, email, nội dung, ngày gửi, tình trạng)
- button trở về 

xử lý: lấy thông tin người liên hệ từ database bảng phanhoi
- click vào button " trở về " quay về trang danh sách phanhoi.

lưu trữ: không

**Comment by ngochihieu281200** [comment]
đã nhận task
