### ISSUE TITLE
đăng nhập

### ISSUE THREAD

**Issue by ngochihieu281200** [ngochihieu281200/QUANLYRESORT#3]
giao diện: hiển thị form đăng nhập gồm: username(textbox) , password(textbox) , đăng nhập (button) , 
xử lý:  đăng nhập sai báo sai username hoặc password, để trống username và password báo không được để trống username và password. lấy dữ liệu từ database ở phần account để kiểm tra. 
lưu trữ: không.

**Comment by thuando2120** [comment]
đã nhận task
