### ISSUE TITLE
sửa thông tin phòng (ở phòng mới)

### ISSUE THREAD

**Issue by thuando2120** [ngochihieu281200/QUANLYRESORT#36]
giao diện: chọn nhấn vào Edit ở cột cuối cùng trong phần danh sách phòng để vào biểu mẫu sửa thông tin phòng: hiển thị biểu mẫu đầy đủ các thông tin bao gồm mã phòng , loại phòng, hiện trạng*, số điện thoại phòng* , số người tối đa*, ghi chú, tiền phát sinh.
Lý do: khi điền các thông tin bắt buộc phải nhập đầy đủ hiện trạng*, số điện thoại phòng* , số người tối đa*, không được bỏ trống, nếu bỏ trống thì báo lỗi "không thể xử lý các thông tin trống có dấu * " và cập nhật lại thông tin phòng.
save archive: lưu vào bảng danh sách phòng cơ sở dữ liệu.

**Comment by ngochihieu281200** [comment]
đã nhận task

**Comment by ngochihieu281200** [comment]
đã nhận task
