### ISSUE TITLE
giao diện thêm mới khách hàng

### ISSUE THREAD

**Issue by ngochihieu281200** [ngochihieu281200/QUANLYRESORT#59]
Giao diện: hiển thị form thông tin khách hàng: mã khách hàng, tên khách hàng* , ngày sinh, giới tính, địa chỉ* , điện thoại, số CMND*, Email, ghi chú, trạng thái, nút button lưu(thêm), nút làm mới (làm mới lại tất cả), và hiển thị danh sách khách hàng bên dưới form thêm mới khách hàng gồm các trường như: STT, Mã KH, Tên khách hàng, Ngày sinh, Giới tính, Địa chỉ, Điện thoại, Số CMND, Email, Ghi chú , Trạng Thái và Edit.

Xử lý: những thông tin có để dấu * bắt buộc phải điền đầy đủ, không được bỏ trống , nếu bỏ trông thì hiển thị thông báo vui lòng nhập trường này ( những trường có dấu *). số điện thoại bắt buộc nhập đủ 10 số nếu nhập không đúng 10 số thì báo sai định dạng. Số cmnd bắt buộc nhập đúng 12 số không có chữ số, nếu có chữ hoặc thiếu thì báo sai định dạng. Mã khách hàng không được cho nhập vào, nó tự phát sinh theo thứ tự khách hàng. và cập nhật thêm mới khách hàng vào danh sách khách hàng
Lưu trữ: lưu vào database bảng thông tin khách hàng

**Comment by thuando2120** [comment]
đã nhận task
