### ISSUE TITLE
Xoá phòng (ở phòng mới)

### ISSUE THREAD

**Issue by thuando2120** [ngochihieu281200/QUANLYRESORT#68]
Giao diện: hiển thị form mã phòng, loại phòng, hiện trạng*, SĐT phòng*, số người tối đa* , ghi chú, tiền phát sinh, và bảng danh sách phòng gồm: stt, mã phòng,loại phòng , hiện trạng, SĐT, số người tối đa, ghi chú.

xử lý: hiển thị button xóa phòng và xóa phòng nếu nhấn button đó, thông báo xóa thành công đến nhân viên thực hiện xóa phòng.

lưu trữ: không

**Comment by ngochihieu281200** [comment]
đã nhận task
