### ISSUE TITLE
Giao diện thêm chi tiết phòng

### ISSUE THREAD

**Issue by thuando2120** [ngochihieu281200/QUANLYRESORT#71]
Giao diện: hiển thị form điền thông tin chi tiết phòng mới bao gồm ( mã chi tiết phòng, tên chi tiết phòng, giá, loại phòng)
Xử lý: tên chi tiết phòng , giá không được để trống, nếu bỏ trống hiển thị vui lòng nhập tên chi tiết , giá phòng, loại phòng được  lấy từ danh sách loại phòng có sẵn từ database.
Lưu trữ: lưu các thông tin vào database Chitietphong

**Comment by ngochihieu281200** [comment]
đã nhận task
