### ISSUE TITLE
Xoá chi tiết phòng

### ISSUE THREAD

**Issue by thuando2120** [ngochihieu281200/QUANLYRESORT#72]
giao diện : bấm vào edit ở cột cuối bảng danh sách chi tiết phòng để vào form xóa chi tiết  phòng: hiển thị đầy đủ các thông tin: mã chi tiết phòng, tên chi tiết phòng*, loại phòng, giá và button xóa

xử lý: sau khi xóa cập nhật lại danh sách chi tiết  phòng

lưu trữ: không

**Comment by ngochihieu281200** [comment]
đã nhận task
