### ISSUE TITLE
Sửa chi tiết phòng

### ISSUE THREAD

**Issue by thuando2120** [ngochihieu281200/QUANLYRESORT#73]
giao diện: bấm vào edit ở cột cuối bảng danh sách chi tiết phòng để vào form sửa chi tiết phòng: hiển thị đầy đủ các thông tin: mã chi tiết phòng, tên chi tiết phòng*, loại phòng, giá và button lưu(sửa)

xử lý: phần mã chi tiết phòng không được chỉnh sửa , chỉ cho sửa ở tên chi tiết phòng và giá . tên chi tiết phòng không được bỏ trống, bỏ trống sẽ báo vui lòng nhập tên chi tiết phòng.

lưu trữ: lưu thông tin đã chỉnh sửa vào database ở bảng chi tiết phòng.

**Comment by ngochihieu281200** [comment]
đã nhận task

**Comment by ngochihieu281200** [comment]
đã nhận task
