### ISSUE TITLE
thêm mới chức vụ

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#74]
giao diện:  hiển thị form gồm : mã chức vụ , tên chức vụ*. bảng danh sách chức vụ gồm: stt, mã CV, tên CV và Edit

xư lý: tên chức vụ không được bỏ  trống , nếu bỏ trống thì  báo " vui lòng nhập chức vụ".

lưu trữ: lưu vào database ở bảng chức vụ.

**Comment by ngochihieu281200** [comment]
đã nhận task
