### ISSUE TITLE
sửa chức vụ

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#75]
giao diện: nhấn vào  button Edit ở cột cuối cùng của danh sách chức vụ để vào form sửa chức vụ. hiển thị đầy đủ các thông tin chức vụ.

xử lý: không được bỏ trống chức vụ , nếu bỏ trống  thì báo " vui lòng nhập chức vụ " và cập nhật lại thông tin chức vụ .

lưu trữ: lưu thông tin chức vụ đã sửa vào database ở bảng chức vụ.

**Comment by ngochihieu281200** [comment]
đã nhận task
