### ISSUE TITLE
 xóa chức vụ

### ISSUE THREAD

**Issue by VanThach2907** [ngochihieu281200/QUANLYRESORT#76]
giao diện: nhấn  vào nút Chỉnh sửa ở cột cuối cùng của danh sách chức vform để vào biểu mẫu xóa chức vụ. hiển thị đầy đủ các thông tin chức vụ.

xử lý: cập nhật lại danh sách chức vụ sau khi  xóa chức vụ

lưu trữ: không

**Comment by ngochihieu281200** [comment]
đã nhận task
