### ISSUE TITLE
thêm loại phòng mới

### ISSUE THREAD

**Issue by truongloi1005** [ngochihieu281200/QUANLYRESORT#82]
giao diện: hiển thị form gồm: mã loại phòng , tên loại phòng* giá , nút button lưu(thêm) và danh sách loại phòng: stt, mã loại phòng, tên loại phòng , giá, edit.

xử lý: tên loại phòng không được bỏ trống, nếu bỏ trống vui lòng nhập tên loại phòng , giá là dạng option lấy từ database. hiện thị danh sách loại phòng lấy thông tin  từ database đã có sẵn.

lưu trữ: lưu các thông tin vào database ở bảng loại phòng.

**Comment by thuando2120** [comment]
đã nhận task
