### ISSUE TITLE
Thêm mới người dùng nhóm mới

### ISSUE THREAD

**Issue by ngochihieu281200** [ngochihieu281200/QUANLYRESORT#94]
giao diện:  hiển thị form gồm ( người dùng, nhóm người dùng, ghi chú , button lưu(thêm) ), và bảng danh sách người dùng nhóm : stt , người dùng, nhóm người dùng, ghi chú , edit(button edit)

xử lý:  tên người dùng lấy dạng option  ở bảng quản lý người dùng, nhóm người dùng lấy dạng option ở quản lý nhóm người dùng. 

lưu trữ: lưu vào database ở bảng người dùng nhóm

**Comment by ngochihieu281200** [comment]
đã nhận task

**Comment by thuando2120** [comment]
đã nhận task
