### ISSUE TITLE
xóa người dùng nhóm

### ISSUE THREAD

**Issue by ngochihieu281200** [ngochihieu281200/QUANLYRESORT#95]
giao diện: chọn edit ở cột cuối của danh sách người dùng nhóm để vào giao diện xóa người dùng.  hiển thị đầy đủ thông tin người dùng nhóm( người dùng, nhóm người dùng, ghi chú, button xóa )

xử lý: cập nhật lại danh sách người dùng nhóm sao khi đã xóa.

lưu trữ: không

**Comment by ngochihieu281200** [comment]
đã nhận task

**Comment by thuando2120** [comment]
đã nhận task
