### ISSUE TITLE
sửa người dùng nhóm

### ISSUE THREAD

**Issue by ngochihieu281200** [ngochihieu281200/QUANLYRESORT#96]
giao diện: chọn edit ở cột cuối của danh sách người dùng nhóm để vào giao diện sửa người dùng nhóm. hiển thị đầy đủ thông tin người dùng nhóm( người dùng, nhóm người dùng, ghi chú, button lưu (sửa))

xử lý:  cập nhật thành công

lưu trữ: lưu các thông tin đã sữa vào database ở bảng người dùng nhóm

**Comment by ngochihieu281200** [comment]
đã nhận task

**Comment by thuando2120** [comment]
đã nhận task
